# Generated by Django 3.1.4 on 2025-01-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
