# Generated by Django 3.1.4 on 2025-01-31 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(max_length=50)),
                ('product_dis', models.CharField(max_length=100)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
