# Generated by Django 3.1.4 on 2025-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20250206_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_dis',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
