# Generated by Django 3.1.4 on 2025-02-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productdetail_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pic',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dis',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
