# Generated by Django 3.1.4 on 2025-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
