# Generated by Django 4.2.19 on 2025-02-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_cat_id_alter_ordernow_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='product',
            new_name='products',
        ),
    ]
