# Generated by Django 4.2.19 on 2025-02-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_product_bag_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='products',
            new_name='product',
        ),
    ]
