# Generated by Django 4.2.19 on 2025-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_products_bag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='qu',
            field=models.IntegerField(null=True),
        ),
    ]
